Repository gideontong/Destiny, pull requests merged in 2021-02, with the labels that each got.

#6 Front end layout
  destiny-app/.gitignore
  destiny-app/README.md
  destiny-app/package-lock.json
  destiny-app/package.json
  destiny-app/public/favicon.ico
  destiny-app/public/index.html
  destiny-app/public/petfinder.json
  destiny-app/src/App.js
  destiny-app/src/Main.js
  destiny-app/src/components/About.js
  destiny-app/src/components/Adopt.js
  destiny-app/src/components/Nav.js
  destiny-app/src/components/elements/Grid.js
  destiny-app/src/components/elements/Header.js
  destiny-app/src/components/elements/LoadMore.js
  destiny-app/src/components/elements/PetImage.js
  destiny-app/src/components/hooks/fetchMain.js
  destiny-app/src/components/images/paw.png
  destiny-app/src/components/styles/GlobalStyle.js
  destiny-app/src/components/styles/StyledGrid.js
  destiny-app/src/components/styles/StyledHeader.js
  destiny-app/src/components/styles/StyledLoadMore.js
  destiny-app/src/components/styles/StyledPetImage.js
  destiny-app/src/index.js
Labels: component, frontend, help wanted

#8 Passions -> Google Image
  data/passions.json
  scripts/scrape_designepiclife.py
Labels: backend, enhancement

#10 Create basic pets API
  backend/app.py
  backend/webserver/__init__.py
  backend/webserver/routes.py
Labels: backend, enhancement, help wanted, package

#11 Develop Forms as Components
  components/adopt_form.js
  components/demo_form.js
Labels: component
